server:
  port: 8088

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: sample.example
      default-receive-queue: sample.queue

sample:
  rabbitmq:
    exchange: sample.example
    queue: sample.queue
    routingKey: sample.routingKey